### ISSUE TITLE
update table fields with suncalc values

### ISSUE THREAD

**Issue by solarc3po** [olithissen/suncalc_postgres#1]
happy to found this postgresql extension, thanks for your great work.
Just to try to update my table with some suncalc values, but no succes.

How can i handover my timestamp field to suncalc sql statement?
<code>
update iot_pv  pv
SET glo_data_sun_azimut = degrees(azimuth), 
    glo_data_sun_altitude  = degrees(altitude)
from get_sun_position(**pv._time** at TIME zone 'Europe/Berlin',50.911111,6.111111);    
</code>

In selectstatement thsi will work fine but not in update.

Errorcode:
SQL-Fehler [42P10]: ERROR: invalid reference to FROM-clause entry for table "pv"
  Hinweis: There is an entry for table "pv", but it cannot be referenced from this part of the query.
  Position: 135

**Comment by olithissen** [comment]
Out of curiosity: Are your coordinates random or your actual ones? 🙂

The two main functions `get_sun_position` and `get_sun_times` both return tables, which was quite a tricky design decision. The other option would have been to have the functions return a vector with named fields. So in the end, both functions actually return tables as if you performed a `SELECT` statement.

**Idea 1**
From the top of my head this should work. It's a bit of a hack, as you execute the function twice for each row. 

```sql
UPDATE IOT_PV
SET GLO_DATA_SUN_AZIMUT   = (SELECT DEGREES(AZIMUTH)
                             FROM GET_SUN_POSITION(_TIME AT TIME ZONE 'Europe/Berlin', 50.911111, 6.111111)),
    GLO_DATA_SUN_ALTITUDE = (SELECT DEGREES(ALTITUDE)
                             FROM GET_SUN_POSITION(_TIME AT TIME ZONE 'Europe/Berlin', 50.911111, 6.111111));
```

**Idea 2**
You might be able optimize it with a CTE:

```sql
WITH SUN_POSITION AS (SELECT *
                      FROM IOT_PV PV, GET_SUN_POSITION(PV._TIME AT TIME ZONE 'europe/berlin', 50.911111, 6.111111))
UPDATE IOT_PV
SET GLO_DATA_SUN_AZIMUT   = DEGREES(SUN_POSITION.AZIMUTH),
    GLO_DATA_SUN_ALTITUDE = DEGREES(SUN_POSITION.ALTITUDE)
FROM SUN_POSITION
WHERE IOT_PV._TIME= SUN_POSITION._TIME;
```

**Comment by solarc3po** [comment]
Hi olithissen,

works perfect for 200K records with your Idea 1 =>  took just 6 sec to update (with 7 more sun_calc values).
work flawless.

Many thanks & again great work. 

Best Regards Hans

**Comment by olithissen** [comment]
As for the coordinates: Real or random? It'd be too funny to release something into the wild and get the first question basically from next door.

**Comment by solarc3po** [comment]
the cordinates are real, just to avoid to many guest at my house the 111111 are fakes :)
